<?xml version="1.0" encoding="utf-8"?><Database Name="QLBanve" Class="dbQLBanveDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserAdmin" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PassAdmin" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDONHANG" Member="CHITIETDONHANGs">
    <Type Name="CHITIETDONHANG">
      <Column Name="MADONHANG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHIM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDONHANG" Member="DONDATHANG" ThisKey="MADONHANG" OtherKey="MADONHANG" Type="DONDATHANG" IsForeignKey="true" />
      <Association Name="PHIM_CHITIETDONHANG" Member="PHIM" ThisKey="MAPHIM" OtherKey="MAPHIM" Type="PHIM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUDE" Member="CHUDEs">
    <Type Name="CHUDE">
      <Column Name="MACD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENCHUDE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CHUDE_PHIM" Member="PHIMs" ThisKey="MACD" OtherKey="MACD" Type="PHIM" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MADONHANG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DATHANHTOAN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TINHTRANGDONHANG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MAKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MADONHANG" OtherKey="MADONHANG" Type="CHITIETDONHANG" />
      <Association Name="KHACHHANG_DONDATHANG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Taikhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIACHIKH" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DIENTHOAIKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KHACHHANG_DONDATHANG" Member="DONDATHANGs" ThisKey="MAKH" OtherKey="MAKH" Type="DONDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKHUYENMAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAPHIM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENKHUYENMAI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THANKHUYENMAI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ANHKHUYENMAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PHIM_KHUYENMAI" Member="PHIM" ThisKey="MAPHIM" OtherKey="MAPHIM" Type="PHIM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIM" Member="PHIMs">
    <Type Name="PHIM">
      <Column Name="MAPHIM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENPHIM" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TENPHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NSX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DAODIEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QUOCGIA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ANHBIA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ANHPHU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NGAYCAPNHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SOLUONGTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MACD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENCHUDE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PHIM_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MAPHIM" OtherKey="MAPHIM" Type="CHITIETDONHANG" />
      <Association Name="PHIM_KHUYENMAI" Member="KHUYENMAIs" ThisKey="MAPHIM" OtherKey="MAPHIM" Type="KHUYENMAI" />
      <Association Name="PHIM_PHIM" Member="PHIM2" ThisKey="MAPHIM" OtherKey="MAPHIM" Type="PHIM" Cardinality="One" />
      <Association Name="CHUDE_PHIM" Member="CHUDE" ThisKey="MACD" OtherKey="MACD" Type="CHUDE" IsForeignKey="true" />
      <Association Name="PHIM_PHIM" Member="PHIM1" ThisKey="MAPHIM" OtherKey="MAPHIM" Type="PHIM" IsForeignKey="true" />
    </Type>
  </Table>
</Database>